language: node_js
node_js:
  - 'lts/*'
script:
  - npm test
  - npm run build
branches:
  only:
  - master
  - dev
deploy:
  edge:
    branch: v1.8.47
  provider: pages
  repo: pomotroid
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  local-dir: dist
  on:
    branch: master