[build]
  command = "hugo --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION  = "0.157.0"
  HUGO_EXTENDED = "true"
  HUGO_BASEURL  = "https://pomotroid.app"

[context.deploy-preview.environment]
  HUGO_BASEURL = "$DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  HUGO_BASEURL = "$DEPLOY_PRIME_URL"
